# Generated by Django 5.2 on 2025-07-05 22:17

import django.core.validators
import django.db.models.deletion
import localflavor.br.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', localflavor.br.models.BRCPFField(blank=True, help_text='Formato: 000.000.000-00', max_length=14, verbose_name='CPF')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', localflavor.br.models.BRStateField(blank=True, max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('whatsapp', models.CharField(blank=True, help_text='Formato: (99) 99999-9999', max_length=15, validators=[django.core.validators.RegexValidator(message='Formato: (99) 99999-9999', regex='^\\(\\d{2}\\) \\d{5}-\\d{4}$')], verbose_name='WhatsApp')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='fotos/usuarios')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
