# Generated by Django 5.2 on 2025-07-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtítulo')),
                ('badge_text', models.CharField(blank=True, max_length=50, verbose_name='Texto do Badge')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Imagem')),
                ('button_text', models.CharField(default='VER MAIS', max_length=50, verbose_name='Texto do Botão')),
                ('button_url', models.CharField(default='produtos:loja', max_length=200, verbose_name='URL do Botão')),
                ('button_icon', models.CharField(default='fas fa-chevron-right', max_length=50, verbose_name='Ícone do Botão')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Slide do Carrossel',
                'verbose_name_plural': 'Slides do Carrossel',
                'ordering': ['order'],
            },
        ),
    ]
