# Generated by Django 5.2 on 2025-07-05 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselslide',
            name='button_icon',
        ),
    ]
