# Generated by Django 5.2 on 2025-07-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_carouselslide_button_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselslide',
            name='button_filters',
            field=models.CharField(blank=True, help_text='Filtros para aplicar na URL, formato: marca=nissan ou categoria=suv', max_length=200, verbose_name='Filtros (ex: marca=nissan)'),
        ),
        migrations.AddField(
            model_name='carouselslide',
            name='button_icon',
            field=models.CharField(default='fas fa-arrow-right', max_length=50, verbose_name='Ícone do Botão'),
        ),
    ]
