# Generated by Django 5.2 on 2025-07-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_carouselslide_button_filters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='button_filters',
            field=models.CharField(blank=True, max_length=200, verbose_name='Filtros do Botão'),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='button_icon',
            field=models.CharField(default='fas fa-chevron-right', max_length=50, verbose_name='Ícone do Botão'),
        ),
    ]
