# Generated by Django 5.2 on 2025-05-28 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descricao', models.TextField(max_length=500)),
                ('preco', models.DecimalField(decimal_places=3, max_digits=12)),
                ('imagens', models.ImageField(upload_to='fotos/produtos')),
                ('esta_disponivel', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('cambio', models.CharField(choices=[('automatico', 'Automático'), ('manual', 'Manual')], default='manual', max_length=10, verbose_name='Câmbio')),
                ('carroceria', models.CharField(choices=[('sedan', 'Sedã'), ('suv', 'SUV'), ('hatch', 'Hatch'), ('sw', 'Station Wagon'), ('caminhonete', 'Caminhonete'), ('picape', 'Picape'), ('coupe', 'Coupé'), ('convertivel', 'Conversível'), ('minivan', 'Minivan')], max_length=20, verbose_name='Tipo de Carroceria')),
                ('combustivel', models.CharField(choices=[('flex', 'Flex (Gasolina/Álcool)'), ('gasolina', 'Gasolina'), ('alcool', 'Álcool'), ('diesel', 'Diesel'), ('hibrido', 'Híbrido'), ('eletrico', 'Elétrico')], default='flex', max_length=10, verbose_name='Combustível')),
                ('cor', models.CharField(choices=[('branco', 'Branco'), ('preto', 'Preto'), ('prata', 'Prata'), ('cinza', 'Cinza'), ('vermelho', 'Vermelho'), ('azul', 'Azul'), ('verde', 'Verde'), ('amarelo', 'Amarelo'), ('laranja', 'Laranja'), ('marrom', 'Marrom'), ('bege', 'Bege'), ('dourado', 'Dourado'), ('roxo', 'Roxo')], max_length=20, verbose_name='Cor')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano do Veículo')),
                ('quilometragem', models.PositiveIntegerField(verbose_name='Quilometragem')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
