# Generated by Django 5.2 on 2025-07-03 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_aceita_troca_produto_ano_fabricacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagens',
        ),
        migrations.AlterField(
            model_name='produto',
            name='combustivel',
            field=models.CharField(blank=True, choices=[('flex', 'Flex'), ('gasolina', 'Gasolina'), ('diesel', 'Diesel'), ('eletrico', 'Elétrico')], max_length=20, verbose_name='Combustível'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='opcionais',
            field=models.JSONField(blank=True, default=list, verbose_name='Opcionais'),
        ),
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos/produtos')),
                ('ordem', models.IntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_produto', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Imagem do Produto',
                'verbose_name_plural': 'Imagens do Produto',
                'ordering': ['ordem'],
            },
        ),
    ]
