# Generated by Django 5.2 on 2025-07-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_remove_produto_imagens_alter_produto_combustivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='produto_nome',
            field=models.CharField(max_length=200),
        ),
    ]
