# Generated by Django 5.2 on 2025-07-06 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_produto_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.cidade', verbose_name='Cidade'),
        ),
    ]
