# Generated by Django 5.2 on 2025-07-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_alter_produto_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, choices=[('agrale', 'Agrale'), ('alfa_romeo', 'Alfa Romeo'), ('aston_martin', 'Aston Martin'), ('audi', 'Audi'), ('bentley', 'Bentley'), ('bmw', 'BMW'), ('buick', 'Buick'), ('byd', 'BYD'), ('cadillac', 'Cadillac'), ('caoa', 'CAOA'), ('chery', 'Chery'), ('chevrolet', 'Chevrolet'), ('chrysler', 'Chrysler'), ('citroen', 'Citroën'), ('dacia', 'Dacia'), ('daf', 'DAF'), ('daihatsu', 'Daihatsu'), ('dodge', 'Dodge'), ('dongfeng', 'Dongfeng'), ('ds', 'DS'), ('ferrari', 'Ferrari'), ('fiat', 'Fiat'), ('fiat_professional', 'Fiat Professional'), ('ford', 'Ford'), ('geely', 'Geely'), ('gmc', 'GMC'), ('great_wall', 'Great Wall'), ('gurgel', 'Gurgel'), ('haval', 'Haval'), ('hino', 'Hino'), ('honda', 'Honda'), ('hyundai', 'Hyundai'), ('isuzu', 'Isuzu'), ('iveco', 'Iveco'), ('jac', 'JAC'), ('jaguar', 'Jaguar'), ('jeep', 'Jeep'), ('kia', 'Kia'), ('lada', 'Lada'), ('lamborghini', 'Lamborghini'), ('land_rover', 'Land Rover'), ('lexus', 'Lexus'), ('lifan', 'Lifan'), ('lincoln', 'Lincoln'), ('mahindra', 'Mahindra'), ('man', 'MAN'), ('marcopolo', 'Marcopolo'), ('maserati', 'Maserati'), ('mazda', 'Mazda'), ('mercedes', 'Mercedes-Benz'), ('mercedes_benz_trucks', 'Mercedes-Benz Trucks'), ('mini', 'Mini'), ('mitsubishi', 'Mitsubishi'), ('nissan', 'Nissan'), ('opel', 'Opel'), ('outros', 'Outros'), ('peugeot', 'Peugeot'), ('porsche', 'Porsche'), ('puma', 'Puma'), ('ram', 'RAM'), ('renault', 'Renault'), ('rolls_royce', 'Rolls-Royce'), ('saic', 'SAIC'), ('scania', 'Scania'), ('seat', 'Seat'), ('skoda', 'Skoda'), ('smart', 'Smart'), ('ssangyong', 'SsangYong'), ('subaru', 'Subaru'), ('suzuki', 'Suzuki'), ('tata', 'Tata'), ('tesla', 'Tesla'), ('toyota', 'Toyota'), ('troller', 'Troller'), ('volkswagen', 'Volkswagen'), ('volkswagen_trucks', 'Volkswagen Trucks'), ('volvo', 'Volvo'), ('volvo_trucks', 'Volvo Trucks')], max_length=100, verbose_name='Marca'),
        ),
    ]
